import 'dart:async';
import 'dart:math';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
// import 'package:intl/intl.dart'; // Unused
// import 'package:flutter_animate/flutter_animate.dart'; // Unused
import '../services/auth_service.dart';
import '../services/localization_service.dart';
import '../services/firestore_service.dart';
import '../services/theme_service.dart';
import '../models/user_model.dart';
import '../models/todo_model.dart';
import '../core/constants/colors.dart';

import '../widgets/kanban_header.dart';
import '../widgets/kanban_board.dart';
import '../widgets/settings_dialog.dart';
import '../widgets/add_task_sheet.dart';
import '../widgets/voice_dialog.dart';
import '../widgets/pet_widget.dart';
import '../services/voice_service.dart'; // Needed for TaskDraft
import 'login_screen.dart';

class KanbanBoardScreen extends StatefulWidget {
  const KanbanBoardScreen({super.key});

  @override
  State<KanbanBoardScreen> createState() => _KanbanBoardScreenState();
}

class _KanbanBoardScreenState extends State<KanbanBoardScreen> {
  UserModel? _currentUser;
  bool _isLoading = true;
  final ScrollController _scrollController = ScrollController();
  Timer? _autoScrollTimer;
  double _scrollSpeed = 0;

  // Edge threshold for triggering auto-scroll
  static const double _scrollEdgeThreshold = 80.0;
  static const double _maxScrollSpeed = 12.0;

  @override
  void initState() {
    super.initState();
    _loadUserData();
  }

  @override
  void dispose() {
    _autoScrollTimer?.cancel();
    _scrollController.dispose();
    super.dispose();
  }

  void _handleDragUpdate(double globalX) {
    final screenWidth = MediaQuery.of(context).size.width;

    // Calculate scroll speed based on proximity to edge
    // The closer to the edge, the faster the scroll
    if (globalX < _scrollEdgeThreshold) {
      // Near left edge - scroll left (negative)
      final proximity = 1.0 - (globalX / _scrollEdgeThreshold);
      _scrollSpeed = -_maxScrollSpeed * proximity;
      _startContinuousScroll();
    } else if (globalX > screenWidth - _scrollEdgeThreshold) {
      // Near right edge - scroll right (positive)
      final distanceFromEdge = screenWidth - globalX;
      final proximity = 1.0 - (distanceFromEdge / _scrollEdgeThreshold);
      _scrollSpeed = _maxScrollSpeed * proximity;
      _startContinuousScroll();
    } else {
      // Not near any edge - stop scrolling
      _stopAutoScroll();
    }
  }

  void _startContinuousScroll() {
    // Only start a new timer if one isn't already running
    if (_autoScrollTimer != null) return;

    _autoScrollTimer =
        Timer.periodic(const Duration(milliseconds: 16), (timer) {
      if (_scrollController.hasClients && _scrollSpeed != 0) {
        final newOffset = _scrollController.offset + _scrollSpeed;
        final maxScroll = _scrollController.position.maxScrollExtent;

        if (newOffset >= 0 && newOffset <= maxScroll) {
          _scrollController.jumpTo(newOffset);
        } else if (newOffset < 0) {
          _scrollController.jumpTo(0);
        } else if (newOffset > maxScroll) {
          _scrollController.jumpTo(maxScroll);
        }
      }
    });
  }

  void _stopAutoScroll() {
    _autoScrollTimer?.cancel();
    _autoScrollTimer = null;
    _scrollSpeed = 0;
  }

  Future<void> _loadUserData() async {
    final authService = context.read<AuthService>();
    final user = authService.currentUser;

    if (user != null) {
      final userData = await authService.getUserData(user.uid);
      if (mounted) {
        setState(() {
          _currentUser = userData;
          _isLoading = false;
        });
      }
    } else {
      setState(() => _isLoading = false);
    }
  }

  Future<void> _handleSignOut() async {
    final authService = context.read<AuthService>();
    await authService.signOut();
    if (mounted) {
      Navigator.of(context).pushReplacement(
        MaterialPageRoute(builder: (context) => const LoginScreen()),
      );
    }
  }

  void _showAddTodoDialog({
    String? initialTitle,
    TodoPriority? initialPriority,
    DateTime? initialDueDate,
  }) {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (context) => AddTaskSheet(
        initialTitle: initialTitle ??
            '', // Ensure non-null if AddTaskSheet requires String.
        initialPriority: initialPriority,
        initialDueDate: initialDueDate,
        onTaskAdded: () {
          setState(() {});
        },
        onTaskCreate: (title, description, dueDate, priority, category,
            energyLevel) async {
          // Create task logic
          final firestoreService = context.read<FirestoreService>();
          final authService = context.read<AuthService>();

          final newTodo = TodoModel(
            id: '', // Generated by Firestore
            userId: authService.currentUser!.uid,
            title: title,
            description: description ?? '', // Handle nullable description
            status: TodoStatus.todo,
            priority: priority,
            energyLevel: energyLevel,
            category: category,
            dueDate: dueDate,
            createdAt: DateTime.now(),
            // xpReward will be auto-calculated by TodoModel based on priority & category
          );

          await firestoreService.createTodo(newTodo);
        },
      ),
    );
  }

  Future<void> _showVoiceDialog() async {
    showDialog(
      context: context,
      barrierDismissible: true,
      builder: (context) => const VoiceListeningDialog(),
    ).then((result) {
      if (result != null) {
        if (result is TaskDraft) {
          _showAddTodoDialog(
            initialTitle: result.title,
            initialPriority: result.priority,
            initialDueDate: result.dueDate,
          );
        } else if (result is String && result.isNotEmpty) {
          // Fallback for string
          _showAddTodoDialog(initialTitle: result);
        }
      }
    });
  }

  Future<void> _handleTodoDropped(
      TodoModel todo, TodoStatus newStatus, int newIndex) async {
    final firestoreService = context.read<FirestoreService>();
    final authService = context.read<AuthService>();

    // If moving to completed, award XP
    if (newStatus == TodoStatus.completed &&
        todo.status != TodoStatus.completed) {
      var updatedUser = await authService.addXP(
        authService.currentUser!.uid,
        todo.xpReward,
      );

      // Pet Evolution Logic
      if (updatedUser != null && updatedUser.pet != null) {
        var pet = updatedUser.pet!;
        // Shared XP: Pet Level roughly tracks User Level
        // But we want visual evolution.
        PetStage stage = pet.stage;
        bool evolved = false;

        // Evolve to Adult at User Level 5
        if (stage == PetStage.baby && updatedUser.level >= 5) {
          stage = PetStage.adult;
          evolved = true;
        }

        if (evolved) {
          final evolvedPet = pet.copyWith(stage: stage);
          updatedUser = updatedUser.copyWith(pet: evolvedPet);

          await authService.updateUserData(updatedUser);

          if (mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(
                content: Text('✨ Your pet evolved! ✨'),
                backgroundColor: Colors.purpleAccent,
                duration: Duration(seconds: 3),
              ),
            );
          }
        }
      }

      if (updatedUser != null && mounted) {
        setState(() {
          _currentUser = updatedUser;
        });

        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Row(
              children: [
                const Icon(Icons.celebration, color: Colors.white),
                const SizedBox(width: 12),
                Text('🎉 Great job! +${todo.xpReward} XP'),
              ],
            ),
            backgroundColor: AppColors.success,
            behavior: SnackBarBehavior.floating,
            shape:
                RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
            duration: const Duration(seconds: 2),
          ),
        );
      }
    }

    await firestoreService.updateTodoStatus(todo.id, newStatus, newIndex);
  }

  @override
  Widget build(BuildContext context) {
    if (_isLoading) {
      return const Scaffold(
        body: Center(
          child: CircularProgressIndicator(color: AppColors.lightPrimary),
        ),
      );
    }

    if (_currentUser == null) {
      return const LoginScreen();
    }

    return Consumer<ThemeService>(
      builder: (context, themeService, child) {
        final palette = themeService.currentPalette;

        return Scaffold(
          extendBodyBehindAppBar: true,
          body: Container(
            decoration: BoxDecoration(
              gradient: palette.backgroundGradient,
            ),
            child: SafeArea(
              child: Column(
                children: [
                  if (_currentUser != null)
                    KanbanHeader(
                      user: _currentUser!,
                      palette: palette,
                      onSignOut: _handleSignOut,
                      onSettingsTap: _showSettingsDialog,
                    ),
                  _buildXpBar(),
                  const SizedBox(height: 16),
                  _buildPetArea(),
                  const SizedBox(height: 16),
                  Expanded(
                    child: KanbanBoard(
                      scrollController: _scrollController,
                      onTodoDropped: _handleTodoDropped,
                      onTodoDelete: _deleteTodo,
                      onDragUpdate: _handleDragUpdate,
                      onDragEnd: _stopAutoScroll,
                    ),
                  ),
                ],
              ),
            ),
          ),
          floatingActionButton: Column(
            mainAxisAlignment: MainAxisAlignment.end,
            children: [
              FloatingActionButton(
                heroTag: 'voice_btn',
                onPressed: _showVoiceDialog,
                backgroundColor: palette.secondary,
                child: const Icon(Icons.mic_rounded, color: Colors.white),
              ),
              const SizedBox(height: 16),
              FloatingActionButton.extended(
                heroTag: 'add_btn',
                onPressed: _showAddTodoDialog,
                backgroundColor: palette.primary,
                icon: Icon(Icons.add_rounded, color: palette.surface),
                label: Text(
                  'Add Task',
                  style: TextStyle(
                      color: palette.surface, fontWeight: FontWeight.w600),
                ),
              ),
            ],
          ),
        );
      },
    );
  }

  Widget _buildXpBar() {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 20),
      child: Container(
        padding: const EdgeInsets.all(16),
        decoration: BoxDecoration(
          gradient: LinearGradient(
            colors: [
              AppColors.lightPrimary.withValues(alpha: 0.1),
              AppColors.lightAccent.withValues(alpha: 0.1),
            ],
          ),
          borderRadius: BorderRadius.circular(16),
          border:
              Border.all(color: AppColors.lightPrimary.withValues(alpha: 0.2)),
        ),
        child: Column(
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Row(
                  children: [
                    const Icon(Icons.bolt_rounded,
                        size: 20, color: AppColors.lightPrimary),
                    const SizedBox(width: 6),
                    Text(
                      '${_currentUser!.xp} / ${_currentUser!.xpNeeded} XP',
                      style: const TextStyle(
                        fontSize: 13,
                        fontWeight: FontWeight.w600,
                        color: AppColors.lightText,
                      ),
                    ),
                  ],
                ),
                Container(
                  padding:
                      const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                  decoration: BoxDecoration(
                    gradient: AppColors.primaryGradient,
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Text(
                    '${(_currentUser!.progressPercentage * 100).toInt()}%',
                    style: const TextStyle(
                      fontSize: 12,
                      fontWeight: FontWeight.bold,
                      color: Colors.white,
                    ),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 10),
            ClipRRect(
              borderRadius: BorderRadius.circular(10),
              child: LinearProgressIndicator(
                value: _currentUser!.progressPercentage,
                minHeight: 8,
                backgroundColor: AppColors.lightPrimary.withValues(alpha: 0.2),
                valueColor:
                    const AlwaysStoppedAnimation<Color>(AppColors.lightPrimary),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildPetArea() {
    if (_currentUser == null) return const SizedBox.shrink();

    // If user has no pet, show Adopt button
    if (_currentUser!.pet == null) {
      return Padding(
        padding: const EdgeInsets.symmetric(horizontal: 20),
        child: GestureDetector(
          onTap: _adoptPet,
          child: Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: Colors.white.withValues(alpha: 0.6),
              borderRadius: BorderRadius.circular(20),
              border: Border.all(color: AppColors.lightPrimary, width: 2),
            ),
            child: const Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Text('🥁', style: TextStyle(fontSize: 24)),
                SizedBox(width: 12),
                Text(
                  'Adopt a Pet Companion!',
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                    color: AppColors.lightPrimary,
                  ),
                ),
              ],
            ),
          ),
        ),
      );
    }

    // Show Pet Widget
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 20),
      child: PetWidget(
        pet: _currentUser!.pet!,
        // onPetTap removed as per request
      ),
    );
  }

  Future<void> _adoptPet() async {
    if (_currentUser == null) return;
    final loc = context.read<LocalizationService>();

    // Show Choice Dialog
    final PetType? selectedType = await showDialog<PetType>(
      context: context,
      builder: (context) => AlertDialog(
        title: Text(loc.translate('choose_pet')),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            ListTile(
              leading: const Text('🐱', style: TextStyle(fontSize: 32)),
              title: Text(loc.translate('cat')),
              onTap: () => Navigator.pop(context, PetType.cat),
            ),
            ListTile(
              leading: const Text('🐶', style: TextStyle(fontSize: 32)),
              title: Text(loc.translate('dog')),
              onTap: () => Navigator.pop(context, PetType.dog),
            ),
          ],
        ),
      ),
    );

    if (selectedType == null) return;

    final random = Random();
    final newPet = PetModel(
      type: selectedType,
      name: selectedType == PetType.cat ? 'Mochi' : 'Buddy',
      lastFed: DateTime.now(),
      stage: PetStage.baby, // Start as Baby
      variant: random.nextInt(4), // Random variant 0-3
      evolutionProgress: 0,
    );

    final updatedUser = _currentUser!.copyWith(pet: newPet);

    // Optimistic update
    setState(() => _currentUser = updatedUser);

    if (!mounted) return;
    final authService = context.read<AuthService>();
    await authService.updateUserData(updatedUser);
  }

  void _showSettingsDialog() {
    showDialog(
      context: context,
      builder: (context) => const SettingsDialog(),
    );
  }

  Future<void> _deleteTodo(String id) async {
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
        title: const Row(
          children: [
            Icon(Icons.warning_amber_rounded, color: AppColors.error),
            SizedBox(width: 12),
            Text('Delete Task?'),
          ],
        ),
        content: const Text('Are you sure you want to delete this task?'),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context, false),
            child: const Text('Cancel'),
          ),
          ElevatedButton(
            onPressed: () => Navigator.pop(context, true),
            style: ElevatedButton.styleFrom(
              backgroundColor: AppColors.error,
              shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(12)),
            ),
            child: const Text('Delete', style: TextStyle(color: Colors.white)),
          ),
        ],
      ),
    );

    if (confirmed == true && mounted) {
      final firestoreService = context.read<FirestoreService>();
      await firestoreService.deleteTodo(id);
    }
  }
}
